<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE  Stream [
    <!ELEMENT Stream (Network, Thread*)>

    <!ELEMENT Network (Operator*)>
    <!ATTLIST Network
        name CDATA #IMPLIED
    >
    
    <!ELEMENT Thread (InputNode*)>
    <!ATTLIST Thread
        name CDATA #IMPLIED
    >
    
    <!ELEMENT Operator (Parameter*, Input*)>
    <!ATTLIST Operator
        id NMTOKEN #REQUIRED
        package CDATA #REQUIRED
        type CDATA #REQUIRED
        name CDATA #IMPLIED
    >
    
    <!ELEMENT Parameter (ImageFileName | Double | UInt32)>
    <!ATTLIST Parameter
        id NMTOKEN #REQUIRED
    >
    
    <!ELEMENT Input EMPTY>
    <!ATTLIST Input
        id NMTOKEN #REQUIRED
        operator NMTOKEN #REQUIRED
        output NMTOKEN #REQUIRED
    >
    
    <!ELEMENT InputNode EMPTY>
    <!ATTLIST InputNode
        operator NMTOKEN #REQUIRED
        input NMTOKEN #REQUIRED
    >

    <!ELEMENT ImageFileName (#PCDATA)>
    <!ELEMENT Double (#PCDATA)>
    <!ELEMENT UInt32 (#PCDATA)>
    
]>

<Stream>
    <Network name="Sample network">
        <Operator id="0" package="base" type="ConstImage" name="Source image">
            <Parameter id="0">
                <ImageFileName>lenna.png</ImageFileName>
            </Parameter>
        </Operator>
        <Operator id="1" package="base" type="Clip" name="Clip image">
            <Parameter id="0">
                <UInt32>200</UInt32>
            </Parameter>
            <Parameter id="1">
                <UInt32>210</UInt32>
            </Parameter>
            <Parameter id="2">
                <UInt32>100</UInt32>
            </Parameter>
            <Parameter id="3">
                <UInt32>90</UInt32>
            </Parameter>
            <Input id="0" operator="0" output="0"/>
        </Operator>
        <Operator id="2" package="base" type="AdjustRgbChannels" name="White balance">
            <Parameter id="0">
                <Double>0.1</Double>
            </Parameter>
            <Parameter id="1">
                <Double>1.0</Double>
            </Parameter>
            <Parameter id="2">
                <Double>1.5</Double>
            </Parameter>
            <Input id="0" operator="1" output="0"/>
        </Operator>
        <Operator id="3" package="base" type="AdjustRgbChannels" name="Exposure">
            <Parameter id="0">
                <Double>0.8</Double>
            </Parameter>
            <Parameter id="1">
                <Double>0.8</Double>
            </Parameter>
            <Parameter id="2">
                <Double>0.8</Double>
            </Parameter>
            <Input id="0" operator="2" output="0"/>
        </Operator>
    </Network>
    <Thread name="First processing thread">
        <InputNode operator="1" input="0"/>
        <InputNode operator="2" input="0"/>
    </Thread> 
    <Thread name="Second processing thread">
        <InputNode operator="3" input="0"/>
    </Thread> 
</Stream>