=== BillTheBest/stromx/doc/stromx.dtd
<!ELEMENT Stromx (Stream?, Parameters?)>
<!ATTLIST Stromx
    version CDATA #IMPLIED
>

<!ELEMENT Stream (Operator*, Thread*)>
<!ATTLIST Stream
    name CDATA #IMPLIED
>

<!ELEMENT Parameters (Operator*)>

<!ELEMENT Thread (InputConnector*)>
<!ATTLIST Thread
    name CDATA #IMPLIED
>

<!ELEMENT Operator (Parameter*, Input*)>
<!ATTLIST Operator
    id NMTOKEN #REQUIRED
    package CDATA #REQUIRED
    type CDATA #REQUIRED
    name CDATA #IMPLIED
    version CDATA #REQUIRED
>

<!ELEMENT Parameter (Data)>
<!ATTLIST Parameter
    id NMTOKEN #REQUIRED
>

<!ELEMENT Data (#PCDATA)>
<!ATTLIST Data
    type CDATA #REQUIRED
    package CDATA #REQUIRED
    version CDATA #REQUIRED
>

<!ELEMENT Input EMPTY>
<!ATTLIST Input
    id NMTOKEN #REQUIRED
    operator NMTOKEN #REQUIRED
    output NMTOKEN #REQUIRED
>

<!ELEMENT InputConnector EMPTY>
<!ATTLIST InputConnector
    operator NMTOKEN #REQUIRED
    input NMTOKEN #REQUIRED
>

=== BillTheBest/stromx/stromx/core/test/parameters.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Stromx SYSTEM "stromx.dtd">

<Stromx version="0.1.0">
    <Parameters>
        <Operator id="0" package="TestPackage" type="TestOperator" version="0.1.0">
            <Parameter id="0">
                <Data type="UInt32" package="Core" version="0.1.0">5000</Data>
            </Parameter>
            <Parameter id="1">
                <Data type="UInt32" package="Core" version="0.1.0">200</Data>
            </Parameter>
        </Operator>
        <Operator id="1" package="TestPackage" type="TestOperator" version="0.1.0">
            <Parameter id="0">
                <Data type="UInt32" package="Core" version="0.1.0">6000</Data>
            </Parameter>
            <Parameter id="1">
                <Data type="UInt32" package="Core" version="0.1.0">250</Data>
            </Parameter>
        </Operator>
        <Operator id="2" package="TestPackage" type="TestOperator" version="0.1.0">
            <Parameter id="0">
                <Data type="UInt32" package="Core" version="0.1.0">7000</Data>
            </Parameter>
            <Parameter id="1">
                <Data type="UInt32" package="Core" version="0.1.0">300</Data>
            </Parameter>
        </Operator>
    </Parameters>
</Stromx>

=== BillTheBest/stromx/example/camera/camera.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Stromx SYSTEM "stromx.dtd">

<Stromx version="0.1.0">
    <Stream>
        <Operator id="0" package="Base" type="Camera" version="0.1.0"/>
        <Operator id="1" package="Base" type="Buffer" version="0.1.0"/>
        <Operator id="2" package="Base" type="Canny" version="0.1.0">
            <Input id="0" operator="0" output="0"/>
            <Input id="1" operator="1" output="0"/>
        </Operator>
        <Thread>
            <InputConnector operator="2" input="0"/>
            <InputConnector operator="2" input="1"/>
        </Thread> 
    </Stream>
</Stromx>

=== BillTheBest/stromx/example/file/file.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Stromx SYSTEM "stromx.dtd">

<Stromx version="0.1.0">
    <Stream>
        <Operator id="0" package="Runtime" type="Counter" version="0.1.0"/>
        <Operator id="1" package="Runtime" type="PeriodicDelay" version="0.1.0">
            <Parameter id="0">
                <Data type="UInt32" package="Runtime" version="0.1.0">1000</Data>
            </Parameter>
            <Input id="0" operator="0" output="0"/>
        </Operator>
        <Thread>
            <InputConnector operator="1" input="0"/>
        </Thread> 
    </Stream>
</Stromx>

=== BillTheBest/stromx/stromx/runtime/test/dtd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Stromx SYSTEM "stromx.dtd">

<Stromx version="0.1.0">
    <Stream name="TestStream">
        <Operator id="0" package="TestPackage" type="TestOperator" version="0.1.0" name="Number 1">
            <Parameter id="0">
                <Data type="UInt32" package="Runtime" version="0.1.0">5000</Data>
            </Parameter>
            <Parameter id="1">
                <Data type="UInt32" package="Runtime" version="0.1.0">200</Data>
            </Parameter>
            <Parameter id="2">
                <Data package="Runtime" type="Bool" version="0.1.0">0</Data>
            </Parameter>
            <Parameter id="3">
                <Data package="TestPackage" type="TestData" version="0.1.0" file="data.txt"/>
            </Parameter>
        </Operator>
        <Operator id="1" package="TestPackage" type="TestOperator" version="0.1.0" name="Number 2">
            <Parameter id="0">
                <Data type="UInt32" package="Runtime" version="0.1.0">6000</Data>
            </Parameter>
            <Parameter id="1">
                <Data type="UInt32" package="Runtime" version="0.1.0">250</Data>
            </Parameter>
            <Input id="0" operator="0" output="2"/>
            <Input id="1" operator="0" output="3"/>
        </Operator>
        <Operator id="2" package="TestPackage" type="TestOperator" version="0.1.0" name="Number 3">
            <Parameter id="0">
                <Data type="UInt32" package="Runtime" version="0.1.0">7000</Data>
            </Parameter>
            <Parameter id="1">
                <Data type="UInt32" package="Runtime" version="0.1.0">300</Data>
            </Parameter>
            <Input id="0" operator="1" output="2"/>
            <Input id="1" operator="1" output="3"/>
        </Operator>
        <Thread name="Processing thread">
            <InputConnector operator="1" input="0"/>
            <InputConnector operator="1" input="1"/>
            <InputConnector operator="2" input="0"/>
            <InputConnector operator="2" input="1"/>
        </Thread> 
    </Stream>
</Stromx>

=== BillTheBest/stromx/doc/parameters.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Stromx SYSTEM "stromx.dtd">

   <!-- validate: xmllint \-\-valid \-\-noout parameters.xml
                  (remove backslashes)
                  xmllint \-\-dtdvalid stromx.dtd \-\-noout parameters.xml
   -->

<Stromx version="0.1.0">
    <Parameters>
        <Operator id="0" package="Base" type="ConstImage" version="0.1.0" name="Source image">
            <Parameter id="0">
                <Data type="Image" package="Base" version="0.1.0">lenna.png</Data>
            </Parameter>
        </Operator>
        <Operator id="1" package="Base" type="Clip" version="0.1.0" name="Clip image">
            <Parameter id="0">
                <Data type="UInt32" package="Stream" version="0.1.0">200</Data>
            </Parameter>
            <Parameter id="1">
                <Data type="UInt32" package="Stream" version="0.1.0">210</Data>
            </Parameter>
            <Parameter id="2">
                <Data type="UInt32" package="Stream" version="0.1.0">100</Data>
            </Parameter>
            <Parameter id="3">
                <Data type="UInt32" package="Stream" version="0.1.0">90</Data>
            </Parameter>
        </Operator>
        <Operator id="2" package="Base" type="AdjustRgbChannels" version="0.1.0" name="White balance">
            <Parameter id="0">
                <Data type="Double" package="Stream" version="0.1.0">0.1</Data>
            </Parameter>
            <Parameter id="1">
                <Data type="Double" package="Stream" version="0.1.0">1.0</Data>
            </Parameter>
            <Parameter id="2">
                <Data type="Double" package="Stream" version="0.1.0">1.5</Data>
            </Parameter>
        </Operator>
        <Operator id="3" package="Base" type="AdjustRgbChannels" version="0.1.0" name="Exposure">
            <Parameter id="0">
                <Data type="Double" package="Stream" version="0.1.0">0.8</Data>
            </Parameter>
            <Parameter id="1">
                <Data type="Double" package="Stream" version="0.1.0">0.8</Data>
            </Parameter>
            <Parameter id="2">
                <Data type="Double" package="Stream" version="0.1.0">0.8</Data>
            </Parameter>
        </Operator>
    </Parameters>
</Stromx>

=== BillTheBest/stromx/doc/stream.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Stromx SYSTEM "stromx.dtd">

   <!-- validate: xmllint \-\-valid \-\-noout stream.xml
                  (remove backslashes)
                  xmllint \-\-dtdvalid stromx.dtd \-\-noout stream.xml
   -->

<Stromx version="0.1.0">
    <Stream name="Sample stream">
        <Operator id="0" package="Base" type="ConstImage" version="0.1.0" name="Source image">
            <Parameter id="0">
                <Data type="Image" package="Base" version="0.1.0">lenna.png</Data>
            </Parameter>
        </Operator>
        <Operator id="1" package="Base" type="Clip" version="0.1.0" name="Clip image">
            <Parameter id="0">
                <Data type="UInt32" package="Stream" version="0.1.0">200</Data>
            </Parameter>
            <Parameter id="1">
                <Data type="UInt32" package="Stream" version="0.1.0">210</Data>
            </Parameter>
            <Parameter id="2">
                <Data type="UInt32" package="Stream" version="0.1.0">100</Data>
            </Parameter>
            <Parameter id="3">
                <Data type="UInt32" package="Stream" version="0.1.0">90</Data>
            </Parameter>
            <Input id="0" operator="0" output="0"/>
        </Operator>
        <Operator id="2" package="Base" type="AdjustRgbChannels" version="0.1.0" name="White balance">
            <Parameter id="0">
                <Data type="Double" package="Stream" version="0.1.0">0.1</Data>
            </Parameter>
            <Parameter id="1">
                <Data type="Double" package="Stream" version="0.1.0">1.0</Data>
            </Parameter>
            <Parameter id="2">
                <Data type="Double" package="Stream" version="0.1.0">1.5</Data>
            </Parameter>
            <Input id="0" operator="1" output="0"/>
        </Operator>
        <Operator id="3" package="Base" type="AdjustRgbChannels" version="0.1.0" name="Exposure">
            <Parameter id="0">
                <Data type="Double" package="Stream" version="0.1.0">0.8</Data>
            </Parameter>
            <Parameter id="1">
                <Data type="Double" package="Stream" version="0.1.0">0.8</Data>
            </Parameter>
            <Parameter id="2">
                <Data type="Double" package="Stream" version="0.1.0">0.8</Data>
            </Parameter>
            <Input id="0" operator="2" output="0"/>
        </Operator>
        <Thread name="First processing thread">
            <InputNode operator="1" input="0"/>
            <InputNode operator="2" input="0"/>
        </Thread> 
        <Thread name="Second processing thread">
            <InputNode operator="3" input="0"/>
        </Thread> 
    </Stream>
</Stromx>

=== BillTheBest/stromx/python/example/camera.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Stromx SYSTEM "stromx.dtd">

<Stromx version="0.1.0">
    <Stream>
        <Operator id="0" package="Base" type="Camera" version="0.1.0">
            <!-- output image index -->
            <Parameter id="0">
                <Data package="Runtime" type="Bool" version="0.1.0">1</Data>
            </Parameter>
            <!-- image for camera simulator -->
            <Parameter id="1">
                <Data type="Image" package="Base" version="0.1.0" file="lenna.jpg"/>
            </Parameter>
            <!-- software trigger mode -->
            <Parameter id="2">
                <Data type="Enum" package="Runtime" version="0.1.0">1</Data>
            </Parameter>
            <!-- the buffer size is 1 MB -->
            <Parameter id="6">
                <Data type="UInt32" package="Runtime" version="0.1.0">1000000</Data>
            </Parameter>
            <!-- one buffer -->
            <Parameter id="7">
                <Data type="UInt32" package="Runtime" version="0.1.0">1</Data>
            </Parameter>
            <!-- 8-bit grayscale output -->
            <Parameter id="15">
                <Data type="Enum" package="Runtime" version="0.1.0">1</Data>
            </Parameter>
        </Operator>
        <Operator id="1" package="Base" type="Buffer" version="0.1.0">
            <!-- one buffer -->
            <Parameter id="0">
                <Data type="UInt32" package="Runtime" version="0.1.0">1</Data>
            </Parameter>
            <!-- the buffer size is 1 MB -->
            <Parameter id="1">
                <Data type="UInt32" package="Runtime" version="0.1.0">1000000</Data>
            </Parameter>
        </Operator>
        <Operator id="2" package="Base" type="Canny" version="0.1.0">
            <!-- process in place -->
            <Parameter id="0">
                <Data type="Bool" package="Runtime" version="0.1.0">0</Data>
            </Parameter>
            <!-- threshold 1 -->
            <Parameter id="1">
                <Data type="Double" package="Runtime" version="0.1.0">50</Data>
            </Parameter>
            <!-- threshold 2 -->
            <Parameter id="2">
                <Data type="Double" package="Runtime" version="0.1.0">150</Data>
            </Parameter>
            <Input id="0" operator="0" output="0"/>
            <Input id="1" operator="1" output="0"/>
        </Operator>
        <Thread>
            <InputConnector operator="2" input="0"/>
            <InputConnector operator="2" input="1"/>
        </Thread> 
    </Stream>
</Stromx>
