=== BillTheBest/stromx/doc/stromx.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Stromx">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="Stream"/>
        <xs:element minOccurs="0" ref="Parameters"/>
      </xs:sequence>
      <xs:attribute name="version" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
           <xs:pattern value="[0-9]+.[0-9]+.[0-9]+"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="Stream">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Operator"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Thread"/>
      </xs:sequence>
      <xs:attribute name="name"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Parameters">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Operator"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Thread">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="InputConnector"/>
      </xs:sequence>
      <xs:attribute name="name"/>
      <xs:attribute name="color">
        <xs:simpleType>
          <xs:restriction base="xs:string">
           <xs:pattern value="#([0-9a-f]{1,2}){3}"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="Operator">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Parameter"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Input"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="package" use="required"/>
      <xs:attribute name="type" use="required"/>
      <xs:attribute name="name"/>
      <xs:attribute name="version" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
           <xs:pattern value="[0-9]+.[0-9]+.[0-9]+"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="isInitialized" type="xs:boolean"/>
      <xs:attribute name="x" type="xs:decimal"/>
      <xs:attribute name="y" type="xs:decimal"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Parameter">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="Data">
          <xs:attribute name="id" use="required" type="xs:NMTOKEN"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="Data">
    <xs:sequence>
      <xs:element ref="Data"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="Data">
    <xs:complexType mixed="true">
      <xs:attribute name="type" use="required"/>
      <xs:attribute name="package" use="required"/>
      <xs:attribute name="version" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
           <xs:pattern value="[0-9]+.[0-9]+.[0-9]+"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="file"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Input">
    <xs:complexType>
      <xs:attribute name="id" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="operator" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="output" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="InputConnector">
    <xs:complexType>
      <xs:attribute name="operator" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="input" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== BillTheBest/stromx/stromx/runtime/test/parameters.xml
<?xml version="1.0" encoding="UTF-8" ?>

<Stromx version="0.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="stromx.xsd">
    <Parameters>
        <Operator id="0" package="TestPackage" type="TestOperator" version="0.1.0">
            <Parameter id="0">
                <Data type="UInt32" package="Runtime" version="0.1.0">2000</Data>
            </Parameter>
            <Parameter id="1">
                <Data type="UInt32" package="Runtime" version="0.1.0">100</Data>
            </Parameter>
            <Parameter id="3">
                <Data package="TestPackage" type="TestData" version="0.1.0" file="data.txt"/>
            </Parameter>
        </Operator>
        <Operator id="1" package="TestPackage" type="TestOperator" version="0.1.0">
            <Parameter id="0">
                <Data type="UInt32" package="Runtime" version="0.1.0">3000</Data>
            </Parameter>
            <Parameter id="1">
                <Data type="UInt32" package="Runtime" version="0.1.0">150</Data>
            </Parameter>
        </Operator>
        <Operator id="2" package="TestPackage" type="TestOperator" version="0.1.0">
            <Parameter id="0">
                <Data type="UInt32" package="Runtime" version="0.1.0">4000</Data>
            </Parameter>
            <Parameter id="1">
                <Data type="UInt32" package="Runtime" version="0.1.0">200</Data>
            </Parameter>
        </Operator>
    </Parameters>
</Stromx>

=== BillTheBest/stromx/stromx/runtime/test/stream.xml
<?xml version="1.0" encoding="UTF-8" ?>

<Stromx version="0.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="stromx.xsd">
    <Stream name="TestStream">
        <Operator id="0" package="TestPackage" type="TestOperator" version="0.1.0" name="Number 1" x="10.1" y="5.5">
            <Parameter id="0">
                <Data type="UInt32" package="Runtime" version="0.1.0">5000</Data>
            </Parameter>
            <Parameter id="1">
                <Data type="UInt32" package="Runtime" version="0.1.0">200</Data>
            </Parameter>
            <Parameter id="2">
                <Data package="Runtime" type="Bool" version="0.1.0">0</Data>
            </Parameter>
            <Parameter id="3">
                <Data package="TestPackage" type="TestData" version="0.1.0" file="data.txt"/>
            </Parameter>
        </Operator>
        <Operator id="1" package="TestPackage" type="TestOperator" version="0.1.0" name="Number 2">
            <Parameter id="0">
                <Data type="UInt32" package="Runtime" version="0.1.0">6000</Data>
            </Parameter>
            <Parameter id="1">
                <Data type="UInt32" package="Runtime" version="0.1.0">250</Data>
            </Parameter>
            <Input id="0" operator="0" output="2"/>
            <Input id="1" operator="0" output="3"/>
        </Operator>
        <Operator id="2" package="TestPackage" type="TestOperator" version="0.1.0" name="Number 3">
            <Parameter id="0">
                <Data type="UInt32" package="Runtime" version="0.1.0">7000</Data>
            </Parameter>
            <Parameter id="1">
                <Data type="UInt32" package="Runtime" version="0.1.0">300</Data>
            </Parameter>
            <Input id="0" operator="1" output="2"/>
            <Input id="1" operator="1" output="3"/>
        </Operator>
        <Operator id="3" package="TestPackage" type="TestOperator" version="0.1.0" isInitialized="false" name="Number 4" x="20" y="10">
            <Parameter id="0">
                <Data type="UInt32" package="Runtime" version="0.1.0">8000</Data>
            </Parameter>
        </Operator>
        <Thread name="Processing thread" color="#ff00ee">
            <InputConnector operator="1" input="0"/>
            <InputConnector operator="1" input="1"/>
            <InputConnector operator="2" input="0"/>
            <InputConnector operator="2" input="1"/>
        </Thread> 
	<Thread name="Empty thread"/>
    </Stream>
</Stromx>
